name: Cypress Parallel Tests (No Dashboard)

on: [push]

jobs:
  test:
    name: Cypress tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        threads: [1, 2, 3]  # 3 parallel jobs
        include:
          # Assign weights if some tests are heavier
          - threads: 1
            weight: 40  # Thread 1 gets 40% of tests
          - threads: 2
            weight: 40  # Thread 2 gets 30%
          - threads: 3
            weight: 20  # Thread 3 gets 20%
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress tests
        run: |
          TOTAL_MACHINES=${{ strategy.job-total }}
          THIS_MACHINE=${{ strategy.job-index }}
          npx cypress run \
            --browser chrome \
            --env thread=${{ matrix.thread }},totalThreads=${{ matrix.threads }},threadWeight=${{ matrix.weight }}