name: Cypress Parallel Tests (No Dashboard)

on: [push]

jobs:
  test:
    name: Cypress tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]  # 3 parallel jobs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress tests
        run: |
          TOTAL_MACHINES=${{ strategy.job-total }}
          THIS_MACHINE=${{ strategy.job-index }}
          npx cypress run --browser chrome \
            --env split=$THIS_MACHINE,total=$TOTAL_MACHINES