name: Master Cypress Trigger test

on:
  push:
    branches:
      - main

jobs:
  trigger-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cypress E2E Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: bm-santosh/cypressGithubActionLearning
          event-type: trigger-cypress-e2e
          client-payload: {}

  trigger-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cypress Smoke Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: bm-santosh/cypressGithubActionLearning
          event-type: trigger-cypress-smoke
          client-payload: {}